###

GET http://localhost:3000/
Content-Type: application/json


###
### get list of standards

GET http://localhost:3000/standards
Content-Type: application/json


###
### get specific standard

GET http://localhost:3000/standards/20
Content-Type: application/json


###
### get seasons of special standard

GET http://localhost:3000/standards/20/seasons
Content-Type: application/json


###
### get questions of season of special standard

GET http://localhost:3000/standards/20/seasons/questions
Content-Type: application/json


###
### get questions of special season of special standard

GET http://localhost:3000/standards/20/seasons/20/questions
Content-Type: application/json


###

POST http://localhost:3000/home/search/branches HTTP/1.1
content-type: application/json

{
    "search" : "فن"
}