POST http://localhost:3000/auth/login 
Content-Type:  application/json

{
  "to" : "09381308994",
  "text" : "سلام ، خوبی ؟"
}


###

POST http://192.168.161.2:3000/auth/login 
Content-Type:  application/json

{
  "phone" : "09381308994",
  "sms" : "103969"
}


###

POST http://localhost:3000/auth/signup 
Content-Type:  application/json

{
  "to" : "09381308994"
}

###

POST https://fanniherfei.herokuapp.com/auth/login
Content-Type: application/json

{
  "to" : "09381308994"
}