POST http://localhost:3000/login 
Content-Type:  application/json

{
  "to" : "09381308994",
  "text" : "سلام ، خوبی ؟"
}


###

POST http://localhost:3000/login 
Content-Type:  application/json

{
  "to" : "09381308994",
  "text" : "Hello Sajjad"
}