POST http://localhost:3000/users/check
Content-Type: application/json

{
  "phone_number" : "09381308994" ,
  "sms" : "345876"
}

###

GET http://localhost:3000/users/deleteAll

###

POST http://localhost:3000/users/create
Content-Type: application/json

{
  "username" : "sajjad", 
  "phone_number" : "09381308994",
  "sms" : "568954",
  "province" : "مازندران",
  "city" : "نکا",
  "gender" : "male",
  "verified" : true,
  "blue_tick" : true,
  "image_url" : "url"
}


###


POST http://localhost:3000/users/create
Content-Type: application/json

{
  "username" : "ali", 
  "phone_number" : "09112529820",
  "sms" : "657432",
  "province" : "اصفهان",
  "city" : "کاشان",
  "gender" : "female",
  "verified" : false,
  "blue_tick" : false,
  "image_url" : "url"
}


###


POST http://localhost:3000/users/create
Content-Type: application/json

{
  "username" : "hasan", 
  "phone_number" : "09123261512",
  "sms" : "980768",
  "province" : "گلستان",
  "city" : "گرگان",
  "gender" : "male",
  "verified" : true,
  "blue_tick" : false,
  "image_url" : "url"
}


###

POST http:localhost:3000/users/update
Content-Type: application/json

{
  "province" : "مازندران",
  "city" : "نکا",
}


###

POST http//:localhost:3000/users/update
Content-Type: application/json

{
  "province" : "تهران",
  "city" : "دماوند",
}

###

POST http//:localhost:3000/users/updateImage
Content-Type: application/json

{
  "phone_number" : "09381308994" ,
  "sms" : "345876",
  "image" : "image content here"
}

###

